---
title: "Publication code"
author: "Songyan Yu"
date: "07/07/2020"
output: word_document
---

## Auto calibration R code

```{r echo=TRUE, eval=FALSE}
# Auto-calibration of DYRESM-CAEDYM using the dycdTools package
library(dycdTools)
autoCalibration(cal.para = "Calibration parameters.csv",
                combination = "all",
                model.var = c("TEMP"),
                obs.data = "Obs data_tempolate.csv",
                objective.function = c("nse"),
                start.date="2002-01-23",
                end.date="2016-12-31",
                dycd.wd = "DYCD_Okaraka",
                dycd.output = "DYCD_Okareka/DYsim.nc",
                file_name = "Auto-calibration.csv")
```

## Heat map of NSE values for different combinations of parameters' values

```{r echo=TRUE,eval=FALSE}
# Read in model auto-calibration results
calibration<-read.csv("Auto-calibration.csv")
colnames(calibration)[4]<-"nse.temp"

# Heat map
library(ggplot2)
library(dplyr)

calibration%>%
  ggplot(aes(x=wse,y=vmc,fill=nse.temp))+
  geom_tile()+
  scale_fill_distiller(palette = "PuBu",direction = 1)+
  facet_grid(~lec)+
  xlab("Wind stirring efficiency")+
  ylab("Vertical mixing coefficient")+
  labs(title="Light extinction coefficient",fill="NSE")+
  theme_bw()+
  theme(plot.title = element_text(size=11,hjust = 0.5))+
  ggsave(filename = "Heatmap of NSE values for the temperature simulation.png")
```


## Contour plot

```{r echo=TRUE,eval=FALSE}
# Extract temperature simulations
var.values<-extract.output(dycd.output = "DYCD_Okareka/DYsim.nc",
                           var.extract = c("TEMP"))

for(i in 1:length(var.values)){
  expres<-paste0(names(var.values)[i],"<-data.frame(var.values[[",i,"]])")
  eval(parse(text=expres))
}

# Interpolation of temperature across water column at an interval of 0.5 m
temp.interpolated<-interpol(layerHeights = dyresmLAYER_HTS_Var,
                            var = dyresmTEMPTURE_Var,
                            min.dept = 0,max.dept = 33,by.value = 0.5)

# Read in observed water quality data
obs.okareka<-read.csv("Obs data_tempolate.csv")
obs.okareka$Date<-as.Date(obs.okareka$Date,format="%d/%m/%Y")
obs.temp<-obs.okareka[,c(1,2,3)]

# Contour plot
contour.plot(sim = temp.interpolated,
             obs = obs.temp,
             file_name = "contour_temp.png",
             start.date="2002-01-01",
             end.date="2016-12-31",
             legend.title = "T\n(\u00B0C)",
             min.depth = 0,
             max.depth = 33,
             by.value = 0.5)
```

## Profile plot

```{r echo=TRUE,eval=FALSE}
# Profile plot
profile.plot(sim=temp.interpolated,
             obs = obs.temp,
             sim.start = "2002-01-23",
             sim.end = "2016-12-31",
             plot.start = "2002-01-23",
             plot.end = "2002-12-31",
             file_name = "profile plot_temp.png",
             min.depth = 0,
             max.depth = 33,
             by.value = 0.5,
             xlabel = "Temperature \u00B0C",
             height = 4,
             width = 7)
```

## Time series plot

```{r echo=TRUE, eval=FALSE}
# Time serise plot
ts.plot(sim = temp.interpolated,
        obs = obs.temp,
        file_name=paste0("TS_temp.png"),
        target.depth=c(1,14,30),
        sim.start="2002-01-23",
        sim.end="2016-12-31",
        plot.start = "2002-01-23",
        plot.end="2012-12-31",
        min.depth=0,
        max.depth=33,
        by.value=0.5,
        ylabel="Temperature \u00B0C",
        height = 4,
        width = 7)
```

## Scater plot

```{r echo=TRUE,eval=FALSE}
# Scatter plot
scatter.plot(sim=temp.interpolated,
             obs=obs.temp,
             sim.start="2002-01-23",
             sim.end="2016-12-31",
             plot.start = "2002-01-23",
             plot.end="2012-12-31",
             file_name = "scatter plot_temp.png",
             min.depth = 0,
             max.depth = 33,
             by.value = 0.5,
             height = 4,
             width = 7)
```

